### ISSUE TITLE
Anzeige der User im WiW bei der Szenenerstellung

### ISSUE THREAD

**Issue by yoknome** [katjalennartz/scenetracker#3]
Wenn User während der Szenenerstellung auf die vorgeschlagenen Playpartner Klicken, wird in der DB die user activity auf unbekannt gesetzt und es verlinkt auf die /getusernames.php 
![image](https://github.com/katjalennartz/scenetracker/assets/47323658/f0538b0c-2733-44c9-a7af-fc0210cdc8bb)
Wenn andere user oder gar Gäste da dann drauf klicken, werden sie auf eine weiße Seite geleitet, die ein json mit allen Usernamen anzeigt. Die ist auch für Gäste einsehbar. 

Wir würden uns freuen, wenn das behoben werden würde.

Viele Grüße
yoknome

**Comment by katjalennartz** [comment]
ist gefixed :)
